keep the 'seed' dir around

diff --git a/bin/do-reboot b/bin/do-reboot
--- a/bin/do-reboot
+++ b/bin/do-reboot
@@ -25,7 +25,13 @@ if [ -n "$save" ]; then
 fi
 
 if $clean; then
-   rm -Rf /var/lib/cloud || fail "failed clean"
+   # clean but leave the seed directory (lxc)
+   ( set -e;
+     cd /var/lib/cloud
+     for i in *; do
+         [ "$i" = "seed" ] && continue
+         rm -Rf "$i"
+     done ) || fail "failed clean of /var/lib/cloud"
    error "cleared /var/lib/cloud"
 fi
 
