lxc-proposed-snapshot: drop support for lxc < 2.1, minor changes.
Support for lxc < 2.1 required using mount-image-callback support
for lxd.  Support for lxd is now removed from mount-image-callback,
so there is not really a way to get this working.  The fallout is
that we cannot use lxd that ships in distro on xenial.  The solution
there is to suggest the snap for lxd.

Other changes here:
 * better debug messages
 * add and use 'find_command' to find lxc-pstart in the same directory
   as lxc-proposed-snapshot.

diff --git a/bin/lxc-proposed-snapshot b/bin/lxc-proposed-snapshot
--- a/bin/lxc-proposed-snapshot
+++ b/bin/lxc-proposed-snapshot
@@ -51,12 +51,13 @@ debug() {
 }
 
 enable_proposed() {
-    local rel="" line=""
+    local rel="" line="" file="/etc/apt/sources.list.d/proposed.list"
     rel=$(lsb_release -sc)
     line=$(awk '$1 == "deb" && $2 ~ /ubuntu.com/ {
           printf("%s %s %s-proposed main universe\n", $1, $2, rel); exit(0) };
           ' "rel=$rel" /etc/apt/sources.list)
-    echo "$line" > "/etc/apt/sources.list.d/proposed.list" ||
+    debug 1 "Enabling proposed in $file: $line"
+    echo "$line" > "$file" ||
         { error "failed enabling proposed with '$line'"; return 1; }
 }
 
@@ -64,9 +65,19 @@ add_archives() {
     local debline="" rel="$(lsb_release -sc)"
     for debline in "$@"; do
         debline=$(echo "$debline" | sed "s,RELEASE,$rel,")
-        debug 1 "enabling $debline"
+        debug 1 "enabling '$debline' via apt-add-repository"
         apt-add-repository -y "$debline" || return
     done
+}
+
+find_command() {
+    local cmd="$1" mydir="${0%/*}" fpath=""
+    command -v "$cmd" >/dev/null 2>&1 && _RET="$cmd" && return 0
+    [ -x "$mydir/$cmd" ] && _RET="$mydir/$cmd" && return 0
+    fpath=$(readlink -f "$0")
+    mydir="${fpath%/*}"
+    [ -x "$mydir/$cmd" ] && _RET="$mydir/$cmd" && return 0
+    return 1
 }
 
 chrooted() {
@@ -174,6 +185,20 @@ main() {
     local src="ubuntu-daily:$release"
     clean="$cname"
 
+    local lxc_ver="" cmd=""
+    lxc_ver=$(lxc --version) || { error "lxc --version failed"; return 1; }
+    debug 1 "lxc client version = $lxc_ver"
+
+    case "$lxc_ver" in
+        1.*|2.0.*) error "Unsupported lxc version $lxc_ver"; return 1;;
+        2.1.*|3.*) :;;
+        *) error "Unknown lxc version $lxc_ver"; return 1;;
+    esac
+
+    find_command lxc-pstart ||
+        { error "Unable to find command 'lxc-pstart'."; return 1; }
+    cmd="$_RET"
+
     if [ "$publish" = "true" ]; then
         pubname="$cname"
         cname="${cname}-${RANDOM}${RANDOM}"
@@ -183,23 +208,11 @@ main() {
     debug 1 "initializing container $cname"
     lxc init "$src" "$cname" || {
         error "failed to create $cname from $src"
-        return
+        return 1
     }
     CONTAINER_NAME="$clean"
 
-    local lxc_ver="" cmd=""
-    lxc_ver=$(lxc --version)
-
-    if dpkg --compare-versions $lxc_ver ge 2.17; then
-        cmd=( lxc-pstart "$cname" -- )
-    else
-        # avoid sudo prompt by following doc at:
-        # https://gist.github.com/smoser/e7d368481687ab39dc08#file-mic-lxd
-        cmd=( sudo mount-image-callback "lxd:$cname" --system-resolvconf
-              mchroot -- )
-    fi
-    "${cmd[@]}" /bin/bash -s chrooted $vflag "${pt[@]}" < "$0" ||
-        return
+    "$cmd" "$cname" -- /bin/bash -s chrooted $vflag "${pt[@]}" < "$0" || return
 
     if [ "$publish" = "true" ]; then
         debug 1 "publishing $cname to alias $pubname"
