Manual verification of GCE along with some small script changes

diff --git a/sru-scripts/manual/gce-sru b/sru-scripts/manual/gce-sru
--- a/sru-scripts/manual/gce-sru
+++ b/sru-scripts/manual/gce-sru
@@ -44,16 +44,16 @@ ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- systemd-analyze blame
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init analyze show
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init analyze blame
 echo 'Networking config'
-ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cat $NETCFG_FILE
+ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cat $NETCFG_FILE || true  # This will fail on xenial
 
 # Upgrade to -proposed cloud-init and reboot
-scp "${SSHOPTS[@]}" PROPOSED_SCRIPT ubuntu@$VM_IP:.
+scp "${SSHOPTS[@]}" $PROPOSED_SCRIPT ubuntu@$VM_IP:.
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP sudo bash ./setup_proposed.sh 2>&1 | egrep 'cloud-init'
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- dpkg-query --show cloud-init
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- sudo hostname SRU-didnt-work
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- sudo rm -f $NETCFG_FILE
-ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- sudo cloud-init clean --logs --reboot
-ssh-keygen -f "/home/ubuntu/.ssh/known_hosts" -R $VM_IP
+ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- sudo cloud-init clean --logs --reboot  || true  # The reboot can cause the ssh command to end abruptly
+ssh-keygen -f $HOME/.ssh/known_hosts -R $VM_IP
 
 sleep 10  # Wait for the instance to actually go down
 while ! ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
@@ -67,14 +67,14 @@ ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- systemd-analyze blame
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init analyze show
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init analyze blame
 echo 'After upgrade Networking config'
-ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cat $NETCFG_FILE
+ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cat $NETCFG_FILE || true  # This will fail on xenial
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init query --format "'cloud-region: {{cloud_name}}-{{region}}'"
 echo "Get cloud-id"
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP cloud-id
 
 echo 'Validating whether metadata is being updated per boot LP:1819913'
 ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- grep 'Update\ datasource' /var/log/cloud-init.log
-ssh "${SSHOPTS[@]}" ubuntu@$VM_IP sudo reboot || true
+ssh "${SSHOPTS[@]}" ubuntu@$VM_IP sudo reboot || true  # The reboot can cause the ssh command to end abruptly
 
 sleep 10
 while ! ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
