ec2: fix whitespace

diff --git a/sru-templates/manual/ec2-sru b/sru-templates/manual/ec2-sru
--- a/sru-templates/manual/ec2-sru
+++ b/sru-templates/manual/ec2-sru
@@ -95,52 +95,52 @@ teardown_network_interface() {
 # set -x outputs each commant to standard error, so an easy way to keen an eye
 # what's going on while saving a clean log file (stdout only) is using tee(1).
 
-    echo "### BEGIN $UBUNTU_RELEASE"
-    EC2_INST=`launch-ec2 --series $UBUNTU_RELEASE -u ${SAMPLE_CLOUDCONFIG} | awk '/Found/{print $5}'`
-    [ -n "$EC2_INST" ] || { echo "Failed to launch ec2 instance!"; exit 1; }
-    sleep 60
+echo "### BEGIN $UBUNTU_RELEASE"
+EC2_INST=`launch-ec2 --series $UBUNTU_RELEASE -u ${SAMPLE_CLOUDCONFIG} | awk '/Found/{print $5}'`
+[ -n "$EC2_INST" ] || { echo "Failed to launch ec2 instance!"; exit 1; }
+sleep 60
 
-    trap "terminate_instance ${EC2_INST}" ERR
-    ssh $SSHOPTS $EC2_INST -- cloud-init status --wait --long
-    ssh $SSHOPTS $EC2_INST -- cat /run/cloud-init/result.json
-    ssh $SSHOPTS $EC2_INST -- ! grep Trace /var/log/cloud-init.log
-    echo "Expect IMDSv2 token headers are being used on all metadata gets. Expect 0 line count"
-    ssh $SSHOPTS $EC2_INST --  '[[ 0 = `grep headers /var/log/cloud-init.log  | grep -c -v X-aws` ]] || exit 1'
-    ssh $SSHOPTS $EC2_INST -- sudo systemd-analyze
-    ssh $SSHOPTS $EC2_INST -- sudo systemd-analyze blame
-    ssh $SSHOPTS $EC2_INST -- sudo cloud-init analyze show
-    ssh $SSHOPTS $EC2_INST -- ! sudo grep Trace /var/log/cloud-init.log
-    scp $SSHOPTS $PROPOSED_SCRIPT $EC2_INST:
-    ssh $SSHOPTS $EC2_INST sudo bash $PROPOSED_SCRIPT 2>&1 | egrep 'cloud-init'
-    ssh $SSHOPTS $EC2_INST sudo hostname something-else
-    ssh $SSHOPTS $EC2_INST -- sudo cloud-init init
-    ssh $SSHOPTS $EC2_INST -- ! grep Trace /var/log/cloud-init.log
-    ssh $SSHOPTS $EC2_INST -- sudo cloud-init clean --logs --reboot || true
-    sleep 60
-    date --utc +%s.%N
-    ssh $SSHOPTS $EC2_INST -- cloud-init status --wait --long; date --utc +%s.%N
-    ssh $SSHOPTS $EC2_INST -- hostname
-    ssh $SSHOPTS $EC2_INST -- ! grep Trace /var/log/cloud-init.log
-    ssh $SSHOPTS $EC2_INST -- sudo systemd-analyze
-    ssh $SSHOPTS $EC2_INST -- sudo cloud-init analyze show
-    if [ "$UBUNTU_RELEASE" = "xenial" ]; then
-       echo "--- Expect warning on xenial for jinja because deb DOES NOT have jinja dep."
-    else
-       echo "--- Expect success on bionic for jinja because deb DOES have jinja dep."
-    fi
-    ssh $SSHOPTS $EC2_INST "cloud-init query --format 'cloud-region: {{cloud_name}}-{{region}}'"
-    
-    echo 'Per LP:1794399 expect we do not see a lot of killing dhclient logs'
-    ssh $SSHOPTS $EC2_INST "grep dhclient /var/log/cloud-init.log"
+trap "terminate_instance ${EC2_INST}" ERR
+ssh $SSHOPTS $EC2_INST -- cloud-init status --wait --long
+ssh $SSHOPTS $EC2_INST -- cat /run/cloud-init/result.json
+ssh $SSHOPTS $EC2_INST -- ! grep Trace /var/log/cloud-init.log
+echo "Expect IMDSv2 token headers are being used on all metadata gets. Expect 0 line count"
+ssh $SSHOPTS $EC2_INST --  '[[ 0 = `grep headers /var/log/cloud-init.log  | grep -c -v X-aws` ]] || exit 1'
+ssh $SSHOPTS $EC2_INST -- sudo systemd-analyze
+ssh $SSHOPTS $EC2_INST -- sudo systemd-analyze blame
+ssh $SSHOPTS $EC2_INST -- sudo cloud-init analyze show
+ssh $SSHOPTS $EC2_INST -- ! sudo grep Trace /var/log/cloud-init.log
+scp $SSHOPTS $PROPOSED_SCRIPT $EC2_INST:
+ssh $SSHOPTS $EC2_INST sudo bash $PROPOSED_SCRIPT 2>&1 | egrep 'cloud-init'
+ssh $SSHOPTS $EC2_INST sudo hostname something-else
+ssh $SSHOPTS $EC2_INST -- sudo cloud-init init
+ssh $SSHOPTS $EC2_INST -- ! grep Trace /var/log/cloud-init.log
+ssh $SSHOPTS $EC2_INST -- sudo cloud-init clean --logs --reboot || true
+sleep 60
+date --utc +%s.%N
+ssh $SSHOPTS $EC2_INST -- cloud-init status --wait --long; date --utc +%s.%N
+ssh $SSHOPTS $EC2_INST -- hostname
+ssh $SSHOPTS $EC2_INST -- ! grep Trace /var/log/cloud-init.log
+ssh $SSHOPTS $EC2_INST -- sudo systemd-analyze
+ssh $SSHOPTS $EC2_INST -- sudo cloud-init analyze show
+if [ "$UBUNTU_RELEASE" = "xenial" ]; then
+   echo "--- Expect warning on xenial for jinja because deb DOES NOT have jinja dep."
+else
+   echo "--- Expect success on bionic for jinja because deb DOES have jinja dep."
+fi
+ssh $SSHOPTS $EC2_INST "cloud-init query --format 'cloud-region: {{cloud_name}}-{{region}}'"
 
-    echo 'Get cloud-id'
-    ssh $SSHOPTS $EC2_INST cloud-id
+echo 'Per LP:1794399 expect we do not see a lot of killing dhclient logs'
+ssh $SSHOPTS $EC2_INST "grep dhclient /var/log/cloud-init.log"
 
-    echo 'Validating whether metadata is being updated per boot LP:1819913'
-    ssh $SSHOPTS $EC2_INST "grep 'Update datasource' /var/log/cloud-init.log"
-    ssh $SSHOPTS $EC2_INST sudo reboot || true
-    sleep 60
-    echo 'After reboot'
-    ssh $SSHOPTS $EC2_INST "grep 'Update datasource' /var/log/cloud-init.log"
-    terminate_instance $EC2_INST
-    echo "### END $UBUNTU_RELEASE"
+echo 'Get cloud-id'
+ssh $SSHOPTS $EC2_INST cloud-id
+
+echo 'Validating whether metadata is being updated per boot LP:1819913'
+ssh $SSHOPTS $EC2_INST "grep 'Update datasource' /var/log/cloud-init.log"
+ssh $SSHOPTS $EC2_INST sudo reboot || true
+sleep 60
+echo 'After reboot'
+ssh $SSHOPTS $EC2_INST "grep 'Update datasource' /var/log/cloud-init.log"
+terminate_instance $EC2_INST
+echo "### END $UBUNTU_RELEASE"
