Update openstack manual sru template

diff --git a/sru-templates/manual/openstack-sru b/sru-templates/manual/openstack-sru
--- a/sru-templates/manual/openstack-sru
+++ b/sru-templates/manual/openstack-sru
@@ -2,10 +2,15 @@
 
 SRU_SERIES="%SRU_SERIES%"
 
+# local values
+LP_USER="%SRU_LP_USER%"
+ADMIN_NET_ID=""
+SSH_KEY=""
+
 cat > sethostname.yaml << EOF
 ## template: jinja
 #cloud-config
-ssh_import_id : [%SRU_LP_USER%]
+ssh_import_id : [$LP_USER]
 hostname: SRU-worked-{{v1.cloud_name}}
 EOF
 
@@ -17,23 +22,29 @@ apt-get update -q
 apt-get install -qy cloud-init
 EOF
 
-ADMIN_NET_ID=`openstack network list -f json | jq -r '.[] | select(.Name == "danielwatkins_admin_net") | .ID'`
-openstack image list --property architecture=x86_64 -f json > images.json
+if [ ! -e "images.json" ]; then
+    openstack image list --property architecture=x86_64 -f json > images.json
+fi
+
+# create a floating ip, keep the IP and floating-ip UUID for cleanup
+FIP=( `openstack floating ip create ext_net -f json | jq -r '. | .floating_ip_address + " " + .id'` )
+VM_IP=${FIP[0]}; FIP_ID=${FIP[1]}
 
 sshopts=( -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR )
-
 for series in $SRU_SERIES; do
   echo "### BEGIN $series"
-
-  VM_IP=`openstack floating ip create ext_net -f json | jq '.floating_ip_address' -r`
+  if [ "$series" = "xenial" ]; then
+    netcfg="/etc/network/interfaces.d/50-cloud-init.cfg"
+  else
+    netcfg="/etc/netplan/50-cloud-init.yaml"
+  fi
 
   # Determine image, launch instance and attach IP address
   image=$(cat images.json | jq -r '.[]|select((.Name|contains("disk1.img")) and (.Name|contains("'$series'"))) | .ID' | tail -n 1)
-  openstack server create --flavor m1.small --image $image --key-name canonical --nic net-id=$ADMIN_NET_ID --user-data sethostname.yaml test-$series --wait
-  ssh-keygen -f "/home/ubuntu/.ssh/known_hosts" -R $VM_IP
+  openstack server create --flavor m1.small --image $image --key-name $SSH_KEY --nic net-id=$ADMIN_NET_ID --user-data sethostname.yaml test-$series --wait
   openstack server add floating ip test-$series $VM_IP
 
-  sleep 10  # Wait for the instance to actually go down
+  sleep 10  # Wait for the instance to boot
   while ! ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
       sleep 5
   done
@@ -46,18 +57,21 @@ for series in $SRU_SERIES; do
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- systemd-analyze blame
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init analyze show
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init analyze blame
+  echo 'Networking config'
+  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cat $netcfg
 
   # Upgrade to -proposed cloud-init and reboot
   scp "${sshopts[@]}" setup_proposed.sh ubuntu@$VM_IP:.
   ssh "${sshopts[@]}" ubuntu@$VM_IP sudo bash ./setup_proposed.sh 2>&1 | egrep 'cloud-init'
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- dpkg-query --show cloud-init
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- sudo hostname SRU-didnt-work
+  ssh "${sshopts[@]}" ubuntu@$VM_IP -- sudo rm -f $netcfg
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- sudo cloud-init clean --logs --reboot
   ssh-keygen -f "/home/ubuntu/.ssh/known_hosts" -R $VM_IP
 
   sleep 10  # Wait for the instance to actually go down
   while ! ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
-      sleep 5
+      sleep 1
   done
 
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- hostname
@@ -66,17 +80,25 @@ for series in $SRU_SERIES; do
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- systemd-analyze blame
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init analyze show
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init analyze blame
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init query --format 'cloud-region: {{cloud_name}}-{{region}}'
+  echo 'After upgrade Networking config'
+  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cat $netcfg
+  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init query --format "'cloud-region: {{cloud_name}}-{{region}}'"
   echo "Get cloud-id"
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-id
   echo 'Validating whether metadata is being updated per boot LP:1819913'
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- "grep 'Update datasource' /var/log/cloud-init.log"
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- sudo reboot || true
+
+  sleep 10  # Wait for the instance to actually go down
+  while ! ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
+      sleep 1
+  done
   echo 'After reboot'
   ssh "${sshopts[@]}" ubuntu@$VM_IP -- "grep 'Update datasource' /var/log/cloud-init.log"
 done
 
+
+openstack floating ip delete $FIP_ID
 for series in $SRU_SERIES; do
   openstack server delete test-$series
 done
-
