oracle: adapt manual script to use sru-vars.template

diff --git a/sru-templates/manual/oracle-sru b/sru-templates/manual/oracle-sru
--- a/sru-templates/manual/oracle-sru
+++ b/sru-templates/manual/oracle-sru
@@ -1,89 +1,81 @@
+#!/bin/bash
 # Manual Oracle upgrade and clean install validation
+set -ex 
 
-SRU_SERIES="%SRU_SERIES%"
+SRU_VARS=./sru-scripts/sru-vars.template
 
-# local values
-LP_USER="%SRU_LP_USER%"
+if [ ! -f $SRU_VARS ]; then
+   echo "Missing config environment file $SRU_VARS."
+   exit 1
+fi
 
-cat > sethostname.yaml << EOF
-## template: jinja
-#cloud-config
-ssh_import_id : [$LP_USER]
-hostname: SRU-worked-{{v1.cloud_name}}
-EOF
+. $SRU_VARS
 
-cat > setup_proposed.sh <<EOF
-#/bin/bash
-mirror=http://archive.ubuntu.com/ubuntu
-echo deb \$mirror \$(lsb_release -sc)-proposed main | tee /etc/apt/sources.list.d/proposed.list
-apt-get update -q
-apt-get install -qy cloud-init
-EOF
+parse_args $0 $@
+assert_expected_vars PROPOSED_SCRIPT SAMPLE_CLOUDCONFIG LP_USER SSHOPTS \
+    NETCFG_FILE
+create_samplecloudconfig
+create_setup_proposed_script
 
-sshopts=( -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR )
-for series in $SRU_SERIES; do
-  echo "### BEGIN $series"
-  if [ "$series" = "xenial" ]; then
-    netcfg="/etc/network/interfaces.d/50-cloud-init.cfg"
-  else
-    netcfg="/etc/netplan/50-cloud-init.yaml"
-  fi
+
+  echo "### BEGIN $UBUNTU_RELEASE"
 
   # TODO: Use the Oracle CLI
-  echo "Please manually launch a $series instance in Oracle and enter its IP address"
+  echo "Please manually launch a $release instance in Oracle and enter its IP address"
   echo "(Don't forget to add your SSH public key to the instance when you launch it.)"
-  read -p "$series IP address: " VM_IP
+  read -p "$release IP address: " VM_IP
 
-  while ! ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
+  while ! ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
       sleep 5
   done
 
   # Capture current state
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- dpkg-query --show cloud-init
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- sudo cat /run/cloud-init/result.json
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- grep Trace /var/log/cloud-init.log
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- systemd-analyze
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- systemd-analyze blame
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init analyze show
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init analyze blame
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- dpkg-query --show cloud-init
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- sudo cat /run/cloud-init/result.json
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- ! grep Trace /var/log/cloud-init.log
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- systemd-analyze
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- systemd-analyze blame
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init analyze show
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init analyze blame
   echo 'Networking config'
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cat $netcfg
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cat $NETCFG_FILE
 
   # Upgrade to -proposed cloud-init and reboot
-  scp "${sshopts[@]}" setup_proposed.sh ubuntu@$VM_IP:.
-  ssh "${sshopts[@]}" ubuntu@$VM_IP sudo bash ./setup_proposed.sh 2>&1 | egrep 'cloud-init'
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- dpkg-query --show cloud-init
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- sudo hostname SRU-didnt-work
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- sudo rm -f $netcfg
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- sudo cloud-init clean --logs --reboot
+  scp "${SSHOPTS[@]}" setup_proposed.sh ubuntu@$VM_IP:.
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP sudo bash ${PROPOSED_SCRIPT} 2>&1 | egrep 'cloud-init'
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- dpkg-query --show cloud-init
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- sudo hostname SRU-didnt-work
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- sudo rm -f $NETCFG_FILE
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- sudo cloud-init clean --logs --reboot || true
   ssh-keygen -f "/home/ubuntu/.ssh/known_hosts" -R $VM_IP
 
   sleep 10  # Wait for the instance to actually go down
-  while ! ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
+  while ! ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
       sleep 1
   done
 
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- hostname
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- "grep Trace /var/log/cloud-init*"
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- systemd-analyze
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- systemd-analyze blame
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init analyze show
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init analyze blame
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- hostname
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- ! grep Trace /var/log/cloud-init.log
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- systemd-analyze
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- systemd-analyze blame
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init analyze show
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init analyze blame
   echo 'After upgrade Networking config'
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cat $netcfg
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init query --format "'cloud-region: {{cloud_name}}-{{region}}'"
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cat $NETCFG_FILE
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init query --format "'cloud-region: {{cloud_name}}-{{region}}'"
   echo "Get cloud-id"
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-id
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-id
   echo 'Validating whether metadata is being updated per boot LP:1819913'
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- "grep 'Update datasource' /var/log/cloud-init.log"
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- sudo reboot || true
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- "grep 'Update datasource' /var/log/cloud-init.log"
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- sudo reboot || true
 
   sleep 10  # Wait for the instance to actually go down
-  while ! ssh "${sshopts[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
+  while ! ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- cloud-init status --wait --long; do
       sleep 1
   done
   echo 'After reboot'
-  ssh "${sshopts[@]}" ubuntu@$VM_IP -- "grep 'Update datasource' /var/log/cloud-init.log"
-done
+  ssh "${SSHOPTS[@]}" ubuntu@$VM_IP -- "grep 'Update datasource' /var/log/cloud-init.log"
+  echo "### END $release"
 
 echo "Don't forget to clean up your instances!"
+
